2021-02-23 14:16:34,626    7404     INFO test_runner.py(154) - 预计并发线程数：2
2021-02-23 14:16:36,803   11244     INFO result.py(65) - 开始测试： test_rejected (test_login.test_saas.MyTest)
2021-02-23 14:16:36,804   11244     INFO test_saas.py(10) - test
2021-02-23 14:16:41,470   10672     INFO result.py(65) - 开始测试： test_login_0_case1 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:16:46,918   11244     INFO test_saas.py(42) - 测试用例标题：双12活动打开1个宝箱
2021-02-23 14:16:47,150   11244     INFO HttpRequests.py(45) - post：https://pre.17kuxiu.com/user/getAnchorCoverAuditInfo
2021-02-23 14:16:47,151   11244     INFO HttpRequests.py(46) - 从请求到接口返回信息耗时：0.220196秒
2021-02-23 14:16:47,151   11244     INFO HttpRequests.py(26) - 接口返回数据：{"retCode":-100004,"retMsg":"头部信息不完整","success":false}
2021-02-23 14:16:47,155   11244    ERROR test_saas.py(52) - 失败：False is not true
2021-02-23 14:16:50,044   11244  WARNING result.py(186) - 测试未通过： test_rejected (test_login.test_saas.MyTest)
Traceback (most recent call last):
  File "D:\auto_saas_20210201\testcase\test_login\test_saas.py", line 49, in test_rejected
    self.assertTrue(r['retCode'] == 200)
AssertionError: False is not true

2021-02-23 14:16:50,044   11244     INFO result.py(86) - 测试结束： test_rejected (test_login.test_saas.MyTest)
2021-02-23 14:16:50,045   11244     INFO result.py(87) - 耗时： 13.239727020263672
2021-02-23 14:16:54,386   10672    ERROR result.py(171) - 测试产生错误： test_login_0_case1 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 40, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 28, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-23 14:16:54,386   10672     INFO result.py(86) - 测试结束： test_login_0_case1 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:16:54,387   10672     INFO result.py(87) - 耗时： 12.915447235107422
2021-02-23 14:16:54,387   10672     INFO result.py(65) - 开始测试： test_login_1_case2 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:04,615   10672    ERROR result.py(171) - 测试产生错误： test_login_1_case2 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 40, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 28, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-23 14:17:04,616   10672     INFO result.py(86) - 测试结束： test_login_1_case2 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:04,617   10672     INFO result.py(87) - 耗时： 10.228391408920288
2021-02-23 14:17:04,617   10672     INFO result.py(65) - 开始测试： test_login_2_case3 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:14,843   10672    ERROR result.py(171) - 测试产生错误： test_login_2_case3 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 40, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 28, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-23 14:17:14,843   10672     INFO result.py(86) - 测试结束： test_login_2_case3 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:14,844   10672     INFO result.py(87) - 耗时： 10.226417779922485
2021-02-23 14:17:14,844   10672     INFO result.py(65) - 开始测试： test_login_3_case4 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:24,890   10672    ERROR result.py(171) - 测试产生错误： test_login_3_case4 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 40, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 28, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-23 14:17:24,890   10672     INFO result.py(86) - 测试结束： test_login_3_case4 (test_login.test_login_demo.LoginDemo)
2021-02-23 14:17:24,890   10672     INFO result.py(87) - 耗时： 10.045882225036621
2021-02-23 14:17:27,417    7404    ERROR test_runner.py(193) - 
Fail	test_rejected (test_login.test_saas.MyTest)
Error	test_login_0_case1 (test_login.test_login_demo.LoginDemo)
Error	test_login_1_case2 (test_login.test_login_demo.LoginDemo)
Error	test_login_2_case3 (test_login.test_login_demo.LoginDemo)
Error	test_login_3_case4 (test_login.test_login_demo.LoginDemo)

2021-02-23 14:17:27,422    7404     INFO test_runner.py(211) - 
测试结束！
运行时间: 0:00:54.147722
共计执行用例数量：5
执行成功用例数量：0
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：4

