2021-02-26 18:38:39,043   16792     INFO test_runner.py(154) - 预计并发线程数：2
2021-02-26 18:38:41,082    4756     INFO result.py(65) - 开始测试： test_rejected (test_login.test_saas.MyTest)
2021-02-26 18:38:41,083    4756     INFO test_saas.py(10) - test
2021-02-26 18:38:46,266   21132     INFO result.py(65) - 开始测试： test_login_00001 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:38:51,208    4756     INFO test_saas.py(42) - 测试用例标题：双12活动打开1个宝箱
2021-02-26 18:38:51,360    4756     INFO HttpRequests.py(45) - post：https://pre.17kuxiu.com/user/getAnchorCoverAuditInfo
2021-02-26 18:38:51,360    4756     INFO HttpRequests.py(46) - 从请求到接口返回信息耗时：0.143196秒
2021-02-26 18:38:51,361    4756     INFO HttpRequests.py(26) - 接口返回数据：{"retCode":-100004,"retMsg":"头部信息不完整","success":false}
2021-02-26 18:38:51,362    4756    ERROR test_saas.py(52) - 失败：False is not true
2021-02-26 18:38:56,416    4756  WARNING result.py(186) - 测试未通过： test_rejected (test_login.test_saas.MyTest)
Traceback (most recent call last):
  File "D:\auto_saas_20210201\testcase\test_login\test_saas.py", line 49, in test_rejected
    self.assertTrue(r['retCode'] == 200)
AssertionError: False is not true

2021-02-26 18:38:56,416    4756     INFO result.py(86) - 测试结束： test_rejected (test_login.test_saas.MyTest)
2021-02-26 18:38:56,416    4756     INFO result.py(87) - 耗时： 15.33321762084961
2021-02-26 18:38:58,582   21132    ERROR result.py(171) - 测试产生错误： test_login_00001 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 52, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 29, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-26 18:38:58,582   21132     INFO result.py(86) - 测试结束： test_login_00001 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:38:58,582   21132     INFO result.py(87) - 耗时： 12.31546688079834
2021-02-26 18:38:58,582   21132     INFO result.py(65) - 开始测试： test_login_00002 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:09,049   21132    ERROR result.py(171) - 测试产生错误： test_login_00002 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 52, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 29, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-26 18:39:09,049   21132     INFO result.py(86) - 测试结束： test_login_00002 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:09,050   21132     INFO result.py(87) - 耗时： 10.466863870620728
2021-02-26 18:39:09,050   21132     INFO result.py(65) - 开始测试： test_login_00003 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:19,100   21132    ERROR result.py(171) - 测试产生错误： test_login_00003 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 52, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 29, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-26 18:39:19,100   21132     INFO result.py(86) - 测试结束： test_login_00003 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:19,100   21132     INFO result.py(87) - 耗时： 10.049149751663208
2021-02-26 18:39:19,101   21132     INFO result.py(65) - 开始测试： test_login_00004 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:29,161   21132    ERROR result.py(171) - 测试产生错误： test_login_00004 (test_login.test_login_demo.LoginDemo)
Traceback (most recent call last):
  File "C:\Users\yu.zhang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 52, in test_login
    self.logout()
  File "D:\auto_saas_20210201\testcase\test_login\test_login_demo.py", line 29, in logout
    self.driver.find_element_by_link_text("退出").click()
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3Install\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"退出"}
  (Session info: chrome=88.0.4324.182)


2021-02-26 18:39:29,162   21132     INFO result.py(86) - 测试结束： test_login_00004 (test_login.test_login_demo.LoginDemo)
2021-02-26 18:39:29,162   21132     INFO result.py(87) - 耗时： 10.061389207839966
2021-02-26 18:39:31,883   16792    ERROR test_runner.py(193) - 
Fail	test_rejected (test_login.test_saas.MyTest)
Error	test_login_00001 (test_login.test_login_demo.LoginDemo)	test_login_00001
Error	test_login_00002 (test_login.test_login_demo.LoginDemo)	test_login_00002
Error	test_login_00003 (test_login.test_login_demo.LoginDemo)	test_login_00003
Error	test_login_00004 (test_login.test_login_demo.LoginDemo)	test_login_00004

2021-02-26 18:39:31,889   16792     INFO test_runner.py(211) - 
测试结束！
运行时间: 0:00:54.097622
共计执行用例数量：5
执行成功用例数量：0
执行失败用例数量：1
跳过执行用例数量：0
产生异常用例数量：4

